config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get 'new_session' => 'sessions#new'
  post 'login' => 'sessions#create', as: :login
  delete 'logout' => 'sessions#destroy', as: :logout
  get 'sign_up' => 'users#new', as: :signup
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :passwords, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  # With this we help retrieve post from the newest to the oldest
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 160 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # With the dependent option we avoid having messages without user, if it
  # decide to, leave our awesome social network :(
  has_many :messages, dependent: :destroy

  # Social Associations
  has_many :active_relationships, class_name: 'Relationship',
                                   foreign_key: 'follower_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship',
                                    foreign_key: 'followed_id',
                                    dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, :user_name, presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :password,
      :length => { :minimum => 5 }
  validates_confirmation_of :password

  # We ensure the emails have the same format to mantain consistency in the DB
  before_save :upcase_email

  def create_following_relationship(user)
    active_relationships.create(followed_id: user.id)
  end

  def destroy_following_relationship(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  private
  def upcase_email
    self.email = email.upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionHelper
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
    @password_form = PasswordForm.new(current_user)
  end

  def create
    @password_form = PasswordForm.new(current_user)
    if @password_form.submit(params[:password_form])
      flash[:success] = 'You have updated your Password'
      redirect_to current_user, success: "Successfully changed password."
    else
      render "new"
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    followed_user = User.find(params[:followed_id])
    if current_user.create_following_relationship(followed_user)
      flash[:success] = "You are following #{followed_user.user_name}"
      redirect_to :back
    else
      flash[:danger] = "There has been some error, please try again later"
    end
  end

  def destroy
    relationship =  Relationship.find(params[:id])
    if relationship.destroy
      flash[:success] = "You no longer follow that user"
      redirect_to :back
    else
      flash[:danger] = "There has been some error, please try again later"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    user = User.find_by(email: params[:session][:email].upcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Welcome back #{user.user_name}"
      redirect_to user
    else
      flash[:danger] = 'There were some errors with the information provide'
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = 'Succesfully Logout. See you soon :)'
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.includes(:messages)
  end

  def show
    @user = User.includes(:messages).find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Platform161 social network :)"
      redirect_to @user
    else
      render :new
    end
  end

  def following
    user = User.find(params[:id])
    @users = user.following
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'You have deleted your account, sorry to see you leave'
    redirect_to root
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password,
      :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.user_name, class: "img-responsive img-circle")
  end
end

app/views/layouts/_flash.html.erb
<% if flash %>
  <% flash.each do |key,value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container container-layout">
    <%= link_to root_path, class: "navbar-brand navbar-brand-layout" do %>
      <%= image_tag 'logo.png' %>
    <%end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if current_user %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platform161</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
</head>
<body>
  <%= render partial: 'layouts/header' %>
  <%= render :partial => "layouts/flash", :locals => {:flash => flash} %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_list.html.erb
<% if messages.any? %>
  <ul class="message-list">
    <% messages.each do |message| %>
      <li class="message-list-item"><%= message.content %> (<%=message.created_at%>)</li>
      <br>
    <% end %>
  </ul>
<% else %>
  <p>No messages publish, What are you waiting for, expread your word :)</p>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: 'btn btn-success btn-sm' %>
<% end %>

app/views/users/_following_buttons.html.erb
<% unless current_user?(user) %>
  <% if current_user.following?(user) %>
    <%= render partial: 'unfollow', locals: { user: user } %>
  <% else %>
    <%= render partial: 'follow', locals: { user: user } %>
  <% end %>
<% end %>

app/views/users/_following_stats.html.erb
<div>
  <%= link_to "#{user.following.count} Following", following_user_path(user) %>
  <%= link_to "#{user.followers.count} Followers", followers_user_path(user) %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
  <%= f.submit "Unfollow", class: 'btn btn-danger btn-sm' %>
<% end %>

app/views/users/_user.html.erb
<li class="list-group-item clearfix">
  <div class="col-xs-12 col-sm-3">
    <%= link_to user_path(user), class: "img-responsive img-circle" do %>
      <%= gravatar_for(user) %>
    <%end %>
  </div>
  <div class="col-xs-12 col-sm-9">
    <span class="name"><%= user.user_name %></span><br/>
    <p>Messages: <%= user.messages.count %></p>
    <%= render partial: 'following_buttons', locals: { user: user } %>
    <%= render partial: 'following_stats', locals: { user: user } %>
</li>

app/views/users/followers.html.erb
<% if @users.any? %>
  <ul class="list-group" id="contact-list">
    <% @users.each_with_index do |user, index| %>
      <%= render partial: 'user', locals: { user: user, index: index + 1 } %>
    <% end %>
  </ul>
<% else %>
    <p>You have no Followers :( try creating interesting messages</p>
<% end %>

app/views/users/following.html.erb
<% if @users.any? %>
  <ul class="list-group" id="contact-list">
    <% @users.each_with_index do |user, index| %>
      <%= render partial: 'user', locals: { user: user, index: index + 1 } %>
    <% end %>
  </ul>
<% else %>
    <p>You are not Following no one, look for someone that you find interesting and click the Follow link</p>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <% if @users.any? %>
        <ul class="list-group" id="contact-list">
          <% @users.each_with_index do |user, index| %>
            <%= render partial: 'user', locals: { user: user } %>
          <% end %>
        </ul>
      <% else %>
          <p>There are no users please create an account and try bring new people :)</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>SignUp</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.full_messages.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% @user.errors.full_messages.each do |error_message| %>
              <li><%= error_message%></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "SignUp", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

<div class="container">
    <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <%= gravatar_for(user) %>
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= @user.user_name %>
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">
          <%= render partial: 'following_buttons', locals: { user: @user } %>
          <%= render partial: 'following_stats', locals: { user: @user } %>
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li>
              <%= link_to new_password_path do %>
                <i class="glyphicon glyphicon-user"></i>
                Password Settings </a>
              <% end %>
            </li>
          </ul>
        </div>
        <!-- END MENU -->
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">
        <%= render partial: 'messages/list', locals: { messages: @user.messages } %>
      </div>
    </div>
  </div>
</div>